drivers: gpu: switch to counters
../drivers/gpu/msm/adreno_a6xx_preempt.c:564:4: error: no member named 'scratch' in 'struct adreno_preemption'
  564 |                         PREEMPT_SCRATCH_ADDR(adreno_dev, KMD_POSTAMBLE_IDX);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/gpu/msm/adreno.h:259:18: note: expanded from macro 'PREEMPT_SCRATCH_ADDR'
  259 |         ((dev)->preempt.scratch.gpuaddr + (id * sizeof(u64)))
      |          ~~~~~~~~~~~~~~ ^
../drivers/gpu/msm/adreno_a6xx_preempt.c:803:29: error: no member named 'scratch' in 'struct adreno_preemption'
  803 |                 u32 *postamble = preempt->scratch.hostptr +
      |                                  ~~~~~~~  ^
2 errors generated.

Signed-off-by: duckyduckg <duckyduckg65@gmail.com>